# Generated by Django 5.1 on 2024-09-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
