# Generated by Django 5.0.7 on 2024-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Food', max_length=100),
        ),
    ]
