# Generated by Django 5.1 on 2024-09-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
