# Generated by Django 5.1 on 2024-09-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
