# Generated by Django 5.1 on 2024-09-02 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product-images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp', 'avif'])]),
        ),
    ]
