# Generated by Django 5.1 on 2024-09-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='cid',
        ),
        migrations.AddField(
            model_name='color',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
