# Generated by Django 5.1 on 2024-09-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
