# Generated by Django 5.1 on 2024-09-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
