# Generated by Django 5.1 on 2024-09-14 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
